version: 2
jobs:
  build:
    docker:
      - image: debian:buster

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            apt-get update
            apt-get install -qy make gcc libtool automake bison flex libreadline-dev

      - run:
          name: Autotools
          command: |
            aclocal
            autoconf
            libtoolize -qi

      - run:
          name: Configure
          command: ./configure --with-readline

      - run:
          name: Build
          command: make

      - run:
          name: Test
          command: make trip
